name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://static.c-t.work/QN_HZ_cowtransfer-file-dea3e1e7-f122-4268-b730-964e4c2915db%252Fexthm-12.0-20220118-UNOFFICIAL-SNAPSHOT-joan-Vanilla.zip?t-s=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJndWlkK3RpbWVzdGFtcCI6Imlsb3ZlY293dHJhbnNmZXIyMDIxXzE2NTYyMDAwMTQ3ODMifQ.h72bSxuZg6unYFGrhevckLGNXZ3XxBD8gbyxXV7i6CI&t-c=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJndWlkK3RpbWVzdGFtcCI6IjIwMjJ8NnwyNnw3In0.xfezvqLQXiodG9mpQMoWf_HHWEbFuWS9bdHu5Qti2uo&user=&ut=&rt=0&rk=ff_55b5b772-1ff3-4690-b2cc-d867ab72aa09&owner=516831dc-a7bc-418b-b8ce-8a2f7a0890da&tid=&batch=1656200014810&attname=exthm-12.0-20220118-UNOFFICIAL-SNAPSHOT-joan-Vanilla.zip
  ROM_NAME: AOSP 
  BUILD_TYPE: ab
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
